[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
decorations = "full"
opacity = 1.0

[font]
size = 20.0

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Medium"

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.fallback]
normal = [
  { family = "JetBrains Mono", style = "Regular" },
  { family = "Noto Sans Mono", style = "Regular" },
  { family = "monospace" }
]
bold = [
  { family = "JetBrains Mono", style = "Bold" },
  { family = "Noto Sans Mono", style = "Bold" },
  { family = "monospace" }
]
italic = [
  { family = "JetBrains Mono", style = "Italic" },
  { family = "Noto Sans Mono", style = "Italic" },
  { family = "monospace" }
]

[colors.primary]
background = "0x1a1a1a"
foreground = "0xe0e0e0"

