[manager]
# Use Flexoki dark theme
theme = "flexoki-dark"

[opener]
edit = [{ run = "nvim \"$@\"", block = true }]
image = [{ run = "imv \"$@\"", orphan = true, desc = "Image Viewer" }]
pdf   = [{ run = "zathura \"$@\"", orphan = true }]

